### ISSUE TITLE
ca-tier.rb:68:in `lookup': undefined local variable or method `s'

### ISSUE THREAD

**Issue by daniel-kelley** [daniel-kelley/ca-r#18]
/home/dkelley/src/ca-r/lib/ca-r/ca-tier.rb:68:in `lookup': undefined local variable or method `s' for #<CA_Tier:0x00005609f36d9658> (NameError)
make: *** [Makefile:40: out/ca_tier.yml] Error 1

**Comment by daniel-kelley** [comment]
Fixed by https://github.com/daniel-kelley/ca-r/pull/19
