### ISSUE TITLE
Invalid byte sequence in US-ASCII in line 1

### ISSUE THREAD

**Issue by daniel-kelley** [daniel-kelley/ca-r#33]
<pre>
/usr/share/ruby/csv/parser.rb:346:in `rescue in parse': Invalid byte sequence in US-ASCII in line 1. (CSV::MalformedCSVError)                                                  
        from /usr/share/ruby/csv/parser.rb:329:in `parse'                                                                                                                      
        from /usr/share/ruby/csv.rb:2345:in `each'                                                                                                                             
        from /usr/share/ruby/csv.rb:2345:in `each'                                                                                                                             
        from /usr/share/ruby/csv.rb:1206:in `block in foreach'
        from /usr/share/ruby/csv.rb:1438:in `open'
        from /usr/share/ruby/csv.rb:1205:in `foreach'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:126:in `convert_covid19cases_test' 
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:245:in `convert_case'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:361:in `convert'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:480:in `gen_all'
        from bin/ca-incidence-all:13:in `<main>'
/usr/share/ruby/csv/parser.rb:229:in `read_chunk': CSV::Parser::InvalidEncoding (CSV::Parser::InvalidEncoding)
        from /usr/share/ruby/csv/parser.rb:93:in `initialize'
        from /usr/share/ruby/csv/parser.rb:765:in `new'
        from /usr/share/ruby/csv/parser.rb:765:in `build_scanner'
        from /usr/share/ruby/csv/parser.rb:330:in `parse'
        from /usr/share/ruby/csv.rb:2345:in `each'
        from /usr/share/ruby/csv.rb:2345:in `each'
        from /usr/share/ruby/csv.rb:1206:in `block in foreach'
        from /usr/share/ruby/csv.rb:1438:in `open'
        from /usr/share/ruby/csv.rb:1205:in `foreach'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:126:in `convert_covid19cases_test' 
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:245:in `convert_case'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:361:in `convert'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:480:in `gen_all'
        from bin/ca-incidence-all:13:in `<main>'
make: *** [Makefile:20: out/process.R] Error 1
</pre>

**Comment by daniel-kelley** [comment]
Looks like the CSV header got changed to all UPPER CASE:
<pre>
1006>head -1 out/covid19cases_test.csv 
DATE,AREA,AREA_TYPE,POPULATION,CASES,CUMULATIVE_CASES,DEATHS,CUMULATIVE_DEATHS,TOTAL_TESTS,CUMULATIVE_TOTAL_TESTS,POSITIVE_TESTS,CUMULATIVE_POSITIVE_TESTS,REPORTED_CASES,CUMULATIVE_REPORTED_CASES,REPORTED_DEATHS,CUMULATIVE_REPORTED_DEATHS,REPORTED_TESTS
</pre>

**Comment by daniel-kelley** [comment]
Junk at beginning, too:
<pre>
00000000  ef bb bf 44 41 54 45 2c  41 52 45 41 2c 41 52 45  |...DATE,AREA,ARE|
00000010  41 5f 54 59 50 45 2c 50  4f 50 55 4c 41 54 49 4f  |A_TYPE,POPULATIO|
00000020  4e 2c 43 41 53 45 53 2c  43 55 4d 55 4c 41 54 49  |N,CASES,CUMULATI|
00000030  56 45 5f 43 41 53 45 53  2c 44 45 41 54 48 53 2c  |VE_CASES,DEATHS,|
00000040  43 55 4d 55 4c 41 54 49  56 45 5f 44 45 41 54 48  |CUMULATIVE_DEATH|
00000050  53 2c 54 4f 54 41 4c 5f  54 45 53 54 53 2c 43 55  |S,TOTAL_TESTS,CU|
00000060  4d 55 4c 41 54 49 56 45  5f 54 4f 54 41 4c 5f 54  |MULATIVE_TOTAL_T|
00000070  45 53 54 53 2c 50 4f 53  49 54 49 56 45 5f 54 45  |ESTS,POSITIVE_TE|
00000080  53 54 53 2c 43 55 4d 55  4c 41 54 49 56 45 5f 50  |STS,CUMULATIVE_P|
00000090  4f 53 49 54 49 56 45 5f  54 45 53 54 53 2c 52 45  |OSITIVE_TESTS,RE|
000000a0  50 4f 52 54 45 44 5f 43  41 53 45 53 2c 43 55 4d  |PORTED_CASES,CUM|
000000b0  55 4c 41 54 49 56 45 5f  52 45 50 4f 52 54 45 44  |ULATIVE_REPORTED|
000000c0  5f 43 41 53 45 53 2c 52  45 50 4f 52 54 45 44 5f  |_CASES,REPORTED_|
000000d0  44 45 41 54 48 53 2c 43  55 4d 55 4c 41 54 49 56  |DEATHS,CUMULATIV|
000000e0  45 5f 52 45 50 4f 52 54  45 44 5f 44 45 41 54 48  |E_REPORTED_DEATH|
000000f0  53 2c 52 45 50 4f 52 54  45 44 5f 54 45 53 54 53  |S,REPORTED_TESTS|
00000100  0a 32 30 32 31 2d 30 37  2d 31 31 2c 53 75 74 74  |.2021-07-11,Sutt|

</pre>

**Comment by daniel-kelley** [comment]
Hand editing the file in the vain hope that this is a stupid one-off problem.

**Comment by daniel-kelley** [comment]
Seesm to have fixed itself.
