### ISSUE TITLE
invalid date

### ISSUE THREAD

**Issue by daniel-kelley** [daniel-kelley/ca-r#34]
```
bin/ca-incidence-all out/covid19cases_test.csv out/
/home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:69:in `parse': invalid date (Date::Error)
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:69:in `skip_date'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:185:in `block in convert_covid19cases_test'
        from /usr/share/ruby/csv/parser.rb:1158:in `emit_row'
        from /usr/share/ruby/csv/parser.rb:903:in `block in parse_quotable_loose'
        from /usr/share/ruby/csv/parser.rb:129:in `block in each_line'
        from /usr/share/ruby/csv/parser.rb:105:in `each_line'
        from /usr/share/ruby/csv/parser.rb:105:in `each_line'
        from /usr/share/ruby/csv/parser.rb:855:in `parse_quotable_loose'
        from /usr/share/ruby/csv/parser.rb:338:in `parse'
        from /usr/share/ruby/csv.rb:2365:in `each'
        from /usr/share/ruby/csv.rb:2365:in `each'
        from /usr/share/ruby/csv.rb:1218:in `block in foreach'
        from /usr/share/ruby/csv.rb:1450:in `open'
        from /usr/share/ruby/csv.rb:1217:in `foreach'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:126:in `convert_covid19cases_test'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:245:in `convert_case'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:361:in `convert'
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:480:in `gen_all'
        from bin/ca-incidence-all:13:in `<main>'
```

**Comment by daniel-kelley** [comment]
Looks like date format change (among other things!):
```
-2020-02-01,Alameda,County,1685886.0,3.0,3.0,0.0,0.0,4.0,4,0.0,0,0.0,0.0,0.0,0.0,
+02/01/2020,Alameda,County,1685886,3,3,0,0,4,4,0,0,0,0,0,0
```
