### ISSUE TITLE
ca-r/lib/ca-r/ca-r.rb:173:in `block in convert_covid19cases_test': oops (RuntimeError)

### ISSUE THREAD

**Issue by daniel-kelley** [daniel-kelley/ca-r#36]
<PRE>
bin/ca-incidence-all out/covid19cases_test.csv out/                             
/home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:173:in `block in convert_covid19cases_test': oops (RuntimeError)                                                        
        from /usr/share/ruby/csv.rb:2557:in `each'                              
        from /usr/share/ruby/csv.rb:1334:in `block in foreach'                  
        from /usr/share/ruby/csv.rb:1610:in `open'                              
        from /usr/share/ruby/csv.rb:1333:in `foreach'                           
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:142:in `convert_covid19cases_test'                                                                         
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:262:in `convert_case'      
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:378:in `convert'           
        from /home/dkelley/src/ca-r/lib/ca-r/ca-r.rb:497:in `gen_all'           
        from bin/ca-incidence-all:13:in `<main>'                                
</PRE>

**Comment by daniel-kelley** [comment]
Case data not being reported

<pre>
1006>head -1 ./out/covid19cases_test.csv 
date,area,area_type,population,deaths,cumulative_deaths,total_tests,cumulative_total_tests,positive_tests,cumulative_positive_tests
</pre>

Can't calculate estimated R without it...

**Comment by daniel-kelley** [comment]
Looks like `positive_tests, cumulative_positive_tests` track case data reasonably well. so will use that instead.

**Comment by daniel-kelley** [comment]
Case data reappeared this week!

**Comment by daniel-kelley** [comment]
See #37, #38
